---

- hosts: ansible-aws-wordpress
  become: true

  tasks:
    - name: Download the latest version of Wordpress
      get_url:
        url: https://wordpress.org/wordpress-{{ wp_version }}.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Unarchive Wordpress into /var/www/html/
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Delete the archive
      file:
        path: /tmp/wordpress.tar.gz
        state: absent

    - name: Set correct owner and group on the DocumentRoot
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0755
