---
- hosts: ansible-aws-wordpress
  become: true

  tasks:
    - name: Install aptitude
      apt: 
        name: aptitude
        state: present

    - name: Upgrade all packages to the latest version
      apt: 
        update_cache: yes 
        upgrade: full
    
    - name: Ensure update-manager-core is installed
      apt: 
        name: update-manager-core 
        state: present

    - name: Run do-release-upgrade non-interactively
      command: do-release-upgrade -f DistUpgradeViewNonInteractive