---
- hosts: ansible-aws-wordpress
  become: true

  tasks:

  - name: Update apt repos
    apt:
      update_cache: yes
  
  - name: Update packages to latest version
    apt:
      name: "*"
      state: latest

  - name: Do some cleaning (apt cache ans orphans packages)
    apt:
      autoclean: yes
      autoremove: yes