---

- name: Download the latest version of Wordpress
  get_url:
    url: https://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Unarchive Wordpress into /var/www/html/
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Delete the archive
  file:
    path: /tmp/wordpress.tar.gz
    state: absent

- name: Download the latest version of Wordpress Social Login
  get_url:
    url: https://downloads.wordpress.org/plugin/miniorange-login-openid.7.3.1.zip
    dest: /tmp/miniorange-login-openid.zip

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Unarchive Wordpress Social Login into /var/www/html/wordpress/wp-content/plugins/
  unarchive:
    src: /tmp/miniorange-login-openid.zip
    dest: /var/www/html/wordpress/wp-content/plugins/
    remote_src: yes

- name: Delete the archive
  file:
    path: /tmp/miniorange-login-openid.zip
    state: absent

- name: Download the latest version of Mailchimp for Wordpress
  get_url:
    url: https://downloads.wordpress.org/plugin/mailchimp-for-wp.4.7.5.zip
    dest: /tmp/mailchimp-for-wp.zip

- name: Unarchive Mailchimp for Wordpress into /var/www/html/wordpress/wp-content/plugins/
  unarchive:
    src: /tmp/mailchimp-for-wp.zip
    dest: /var/www/html/wordpress/wp-content/plugins/
    remote_src: yes

- name: Delete the archive
  file:
    path: /tmp/mailchimp-for-wp.zip
    state: absent

- name: Download the latest version of CiviCRM for Wordpress
  get_url:
    url: https://download.civicrm.org/civicrm-5.22.1-wordpress.zip
    dest: /tmp/civicrm.zip

#- name: Download the latest version of CiviCRM Localizations
#  get_url:
#    url: https://download.civicrm.org/civicrm-5.22.1-l10n.tar.gz
#    dest: /tmp/civicrmlocalizations.tar.gz

#- name: Install curl
#  apt:
#    name: php-curl
#    state: present

#- name: Unarchive CiviCRM for Wordpress into /var/www/html/wordpress/wp-content/plugins/
#  unarchive:
#    src: /tmp/civicrm.zip
#    dest: /var/www/html/wordpress/wp-content/plugins/
#    remote_src: yes

#- name: Unarchive CiviCRM Localizations /var/www/html/wordpress/wp-content/plugins/
#  unarchive:
#    src: /tmp/civicrmlocalizations.tar.gz
#    dest: /var/www/html/wordpress/wp-content/plugins/
#    remote_src: yes

#- name: Delete the archive
#  file:
#    path: /tmp/civicrmlocalizations.tar.gz
#    state: absent

- name: Set correct owner and group on the DocumentRoot
  file:
    path: /var/www/html/
    owner: www-data
    group: www-data
    mode: 0755

- name: Create wp-config.php from Template
  template:
    src: templates/var/www/html/wordpress/wp-config.php
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Create .htaccess from Template
  template:
    src: templates/var/www/html/wordpress/.htaccess
    dest: /var/www/html/wordpress/.htaccess
    owner: www-data
    group: www-data
    mode: '0644'
