---

mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_root_password_update: yes

mysql_databases:
  - name: wordpress
    encoding: utf8
    state: present

mysql_users:
  - name: wpuser
    host: "localhost"
    password: "{{ vault_mysql_user_password }}"
    priv: "wordpress.*:ALL"
    state: present

apache_vhosts:
  - servername: "{{ dns_name }}"
    documentroot: "/var/www/html/wordpress"
    extra_parameters: |
      ErrorLog /var/log/apache2/{{ dns_name }}.error.log
      CustomLog /var/log/apache2/{{ dns_name }}.access.log combined

      RewriteEngine On
      RewriteCond %{HTTPS} off
      RewriteRule (.*) https://%{SERVER_NAME}$1 [R=301,L]

apache_vhosts_ssl:
  - servername: "{{ dns_name }}"
    documentroot: "/var/www/html/wordpress"

    certificate_file: "/etc/letsencrypt/live/{{ dns_name }}/cert.pem"
    certificate_key_file: "/etc/letsencrypt/live/{{ dns_name }}/privkey.pem"
    certificate_chain_file: "/etc/letsencrypt/live/{{ dns_name }}/chain.pem"

    extra_parameters: |
      ErrorLog /var/log/apache2/{{ dns_name }}.error.ssl.log
      CustomLog /var/log/apache2/{{ dns_name }}.access.ssl.log combined

certbot_certs:
  - email: "{{ certbot_mail }}"
    domains:
      - "{{ dns_zone }}"
      - "{{ dns_name }}"

certbot_create_standalone_stop_services: apache2

certbot_create_if_missing: true
