---
- hosts: localhost
  
  tasks:
    - name: Delete record "{{ dns_name }}" in DNS zone "{{ dns_zone }}"
      route53:
        state: absent
        zone: "{{ dns_zone }}"
        record: "{{ dns_name }}"
        type: A
        ttl: 900
        value: "{{ ip_adress }}"