---

php_memory_limit: "256M"
php_max_execution_time: "300"
php_upload_max_filesize: "256M"

php_max_input_time: "120"
php_max_input_vars: "1000"

php_date_timezone: "Australia/Melbourne"

php_expose_php: "Off"
php_enable_apc: true

php_packages:
  - php
  - php-cli
  - php-common
  - php-dev
  - php-gd
  - php-mysql
  - php-mbstring
  - php-pdo
  - php-apcu
  - php-xml
